version: '3.8'
services:
  security_service:
    container_name: security
    image: postgres:alpine
    environment:
      POSTGRES_USER: SECURITY
      POSTGRES_PASSWORD: SECURITY
      POSTGRES_DB: User
    ports:
      - '5437:5432'
    volumes:
      - securityData:/var/lib/postgresql/data


volumes:
  securityData: {}